export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const SET_LOGIN_USER = 'SET_LOGIN_USER';

export const PROJECT_REQUESTED = 'PROJECT_REQUESTED';
export const PROJECT_RECEIVED = 'PROJECT_RECEIVED';

export const PROJECT_PREFERENCES_REQUESTED = 'PROJECT_PREFERENCES_REQUESTED';
export const PROJECT_PREFERENCES_RECEIVED = 'PROJECT_PREFERENCES_RECEIVED';
export const OLD_PROJECT_PREFERENCES_REQUESTED = 'OLD_PROJECT_PREFERENCES_REQUESTED';
export const OLD_PROJECT_PREFERENCES_RECEIVED = 'OLD_PROJECT_PREFERENCES_RECEIVED';

export const RECENTS_REQUESTED = 'RECENTS_REQUESTED';
export const RECENTS_RECEIVED = 'RECENTS_RECEIVED';

export const WORKFLOWS_REQUESTED = 'WORKFLOWS_REQUESTED';
export const WORKFLOWS_RECEIVED = 'WORKFLOWS_RECEIVED';

export const TALK_REQUESTED = 'TALK_REQUESTED';
export const TALK_RECEIVED = 'TALK_RECEIVED';
