export const PROJECT_DATA_REQUESTED = 'PROJECT_DATA_REQUESTED';
export const PROJECT_DATA_RECEIVED = 'PROJECT_DATA_RECEIVED';
export const WORKFLOWS_REQUESTED = 'WORKFLOWS_REQUESTED';
export const WORKFLOWS_RECEIVED = 'WORKFLOWS_RECEIVED';
